apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: front
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: front
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: front                                  # 7
    spec:
       containers:
        - image: patrykzygmunt/spoleczni-front:minikube
          imagePullPolicy: Always                         # 8
          name: front
          ports:
            - containerPort: 80
