apiVersion: v1
kind: Service
metadata:
  name: multimedia-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8070
    nodePort: 31982
  selector:
    app: multimedia
