apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: nodejs
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: patrykzygmunt/nodejs:latest
        imagePullPolicy: Always
        name: nodejs
        ports:
          - containerPort: 3000
