# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pdb-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.6.1
    release: "pdb"
    heritage: "Helm"
type: Opaque
data:
  postgresql-password: "dVBrMXkwZFBLTA=="
---
# Source: postgresql/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdb-postgresql-headless
  labels:
    app: postgresql
    chart: postgresql-8.6.1
    release: "pdb"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: "pdb"
---
# Source: postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdb-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.6.1
    release: "pdb"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: "pdb"
    role: master
---
# Source: postgresql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pdb-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.6.1
    release: "pdb"
    heritage: "Helm"
spec:
  serviceName: pdb-postgresql-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: postgresql
      release: "pdb"
      role: master
  template:
    metadata:
      name: pdb-postgresql
      labels:
        app: postgresql
        chart: postgresql-8.6.1
        release: "pdb"
        heritage: "Helm"
        role: master
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
      # - name: do-something
      #   image: busybox
      #   command: ['do', 'something']

      containers:
        - name: pdb-postgresql
          image: docker.io/bitnami/postgresql:11.7.0-debian-10-r9
          imagePullPolicy: "IfNotPresent"
#          command:
#           - /bin/sh
#           - |
#             PGPASSWORD=secretpassword
#             psql  -U postgres -c  ' CREATE DATABASE spoleczni'
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "secretpassword"
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            - name:  POSTGRES_DB
              value: "spoleczni"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
              subPath:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"