apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: stat
spec:
  replicas: 1                                            # 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: stat
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: stat # 7
    spec:
      containers:
        - image: patrykzygmunt/stat-service:prod
          imagePullPolicy: Always                         # 8
          name: stat
          env:
          - name: KAFKA_URL
            value:   10.0.4.13:9092
          ports:
            - containerPort: 8086
---
  
apiVersion: v1
kind: Service
metadata:
  name: stat-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8086
    nodePort: 31985
  selector:
    app: stat
