apiVersion: v1
kind: Service
metadata:
  name: universe-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    nodePort: 31988
  selector:
    app: universe
